name: ${PROJECT_NAME}

services:
  app:
    container_name: ${PROJECT_NAME}-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: ${PROJECT_NAME}-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${PROJECT_DIR}/docker/data/redis:/data

  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${PROJECT_DIR}/docker/data/postgresql/data:/var/lib/postgresql/data:rw
