basePath: /api/v1
info:
  contact: {}
  description: This is a sample server Petstore server.
  license:
    name: MIT
    url: http://github.com/nazarkhatsko/imgix/LICENSE
  title: IMGIX Swagger API
  version: "1.0"
paths: {}
swagger: "2.0"
